create table public.reviews (
  id bigint generated by default as identity primary key,
  school_code text not null,
  office_code text not null,
  meal_date text not null, -- YYYYMMDD 형식
  meal_type text not null, -- '조식', '중식', '석식'
  rating integer not null check (rating >= 1 and rating <= 5),
  content text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- (선택사항) 빠른 조회를 위한 인덱스 생성
create index reviews_school_lookup_idx on public.reviews (school_code, office_code, meal_date);
